### ISSUE TITLE
[Feature Request] epub format for inline images

### ISSUE THREAD

**Issue by dundundunnn** [thdaemon/pixiv-novel-saver#6]
can you implement "save as epub format" with the inline images, so i can be able to read the story with images on a single file

**Comment by thdaemon** [comment]
As the name "saver" suggests, I made this program because I wanted to back up my collection of novels to prevent them from disappearing from the Internet. I usually use the official Pixiv Mobile App to read novels.
So I don't plan to implement this feature, and, since I plan to refactor the project entirely in Python, these new features may come in a new Python version.
